[colors.primary]
background = "#000000"
foreground = "#cad3f5"
dim_foreground = "#8087a2"
bright_foreground = "#cad3f5"

[colors.cursor]
text = "#000000"
cursor = "#f4dbd6"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#b7bdf8"

[colors.search.matches]
foreground = "#000000"
background = "#a5adcb"

[colors.search.focused_match]
foreground = "#000000"
background = "#a6da95"

[colors.footer_bar]
foreground = "#000000"
background = "#a5adcb"

[colors.hints.start]
foreground = "#000000"
background = "#eed49f"

[colors.hints.end]
foreground = "#000000"
background = "#a5adcb"

[colors.selection]
text = "#000000"
background = "#f4dbd6"

[colors.normal]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"

[colors.bright]
black = "#5b6078"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#a5adcb"

[colors.dim]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"

[[colors.indexed_colors]]
index = 16
color = "#f5a97f"

[[colors.indexed_colors]]
index = 17
color = "#f4dbd6"

