# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  theme:
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - black
  nerdFontsVersion: "3"

customCommands:
  - key: 'U'
    command: 'git submodule update --recursive'
    context: 'global'
    description: 'Update submodules'
    output: log
  - key: 'I'
    command: 'git submodule update --init --recursive'
    context: 'global'
    description: 'Initialize submodules'
    output: log
