wallpaper {
    monitor =
    # https://github.com/basecamp/omarchy/blob/dev/themes/matte-black/backgrounds/1-dark-waters.jpg?raw=true
    path = ~/Pictures/wallpaper/dark-waters.jpg
    fit_mode = cover
}
