windowrule = match:class com.gabm.satty, float true
windowrule = match:class com.gabm.satty, center true
# set this to your leftmost monitor id, otherwise you have to move your cursor to the leftmost monitor
# before executing com.gabm.satty
windowrule = match:class com.gabm.satty, monitor 1

windowrule = match:class 2GIS, workspace name:D silent
windowrule = match:class v4android, workspace name:D silent
windowrule = match:class org.qt-project.qml, workspace name:D silent

windowrule = match:class org.qt-project.qml, float true
