local function get_graph_style()
	return string.match(vim.env.TERM, "kitty") and "kitty" or "ascii"
end

return {
	"NeogitOrg/neogit",
	cmd = {
		"Neogit" --[[ , "Neogit cwd", "Neogit kind", "Neogit commit" ]],
	},
	dependencies = {
		"nvim-lua/plenary.nvim", -- required
		"sindrets/diffview.nvim", -- optional - Diff integration
	},
	keys = {
		{ "<leader>n", "<cmd>Neogit<cr>", desc = "Neogit" },
		{
			"<leader>N",
			function()
				if vim.bo.filetype == "oil" then
					local cur_dir = require("oil").get_current_dir(0)
					require("neogit").open({ cwd = cur_dir })
				else
					require("neogit").open({ cwd = vim.fn.expand("%:p:h") })
				end
			end,
			desc = "Neogit in current buffer directory",
		},
	},
	config = true,
	opts = {
		disable_hint = true,
		use_default_keymaps = false,
		disable_line_numbers = false,
		disable_relative_line_numbers = false,
		graph_style = get_graph_style(),
		mappings = {
			commit_editor = {
				-- ["q"] = "Close", -- NOTE: maybe change
				["<C-s>"] = "Submit",
				["<M-a>"] = "Abort",
				["<C-Up>"] = "PrevMessage",
				["<C-Down>"] = "NextMessage",
				["<M-r>"] = "ResetMessage", -- NOTE: maybe change
			},
			commit_editor_I = {
				["<C-s>"] = "Submit",
				["<M-a>"] = "Abort",
			},
			rebase_editor = {
				["p"] = "Pick",
				["r"] = "Reword",
				["e"] = "Edit",
				["s"] = "Squash",
				["f"] = "Fixup",
				["x"] = "Execute",
				["d"] = "Drop",
				["b"] = "Break",
				-- ["q"] = "Close",
				["<cr>"] = "OpenCommit",
				["<C-Up>"] = "MoveUp",
				["<C-Down>"] = "MoveDown",
				["<C-s>"] = "Submit",
				["<M-a>"] = "Abort",
				["[c"] = "OpenOrScrollUp",
				["]c"] = "OpenOrScrollDown",
			},
			rebase_editor_I = {
				["<C-s>"] = "Submit",
				["<M-a>"] = "Abort",
			},
			finder = {
				["<cr>"] = "Select",
				["<c-c>"] = "Close",
				["<esc>"] = "Close",
				["<c-n>"] = "Next",
				["<c-p>"] = "Previous",
				["<down>"] = "Next",
				["<up>"] = "Previous",
				["<tab>"] = "InsertCompletion",
				["<c-y>"] = "CopySelection",
				["<space>"] = "MultiselectToggleNext",
				["<s-space>"] = "MultiselectTogglePrevious",
				["<c-j>"] = "NOP",
				["<ScrollWheelDown>"] = "ScrollWheelDown",
				["<ScrollWheelUp>"] = "ScrollWheelUp",
				["<ScrollWheelLeft>"] = "NOP",
				["<ScrollWheelRight>"] = "NOP",
				["<LeftMouse>"] = "MouseClick",
				["<2-LeftMouse>"] = "NOP",
			},
			refs_view = {
				["x"] = "DeleteBranch",
			},
			popup = {
				["g?"] = "HelpPopup",
				["A"] = "CherryPickPopup",
				["d"] = "DiffPopup",
				["<M-r>"] = "RemotePopup",
				["P"] = "PushPopup",
				["X"] = "ResetPopup",
				["Z"] = "StashPopup",
				["i"] = "IgnorePopup",
				["<M-t>"] = "TagPopup",
				["<M-b>"] = "BranchPopup",
				["<S-M-b>"] = "BisectPopup",
				["<M-w>"] = "WorktreePopup",
				["c"] = "CommitPopup",
				["<M-f>"] = "FetchPopup",
				["l"] = "LogPopup",
				["<M-m>"] = "MergePopup",
				["p"] = "PullPopup",
				["r"] = "RebasePopup",
				["<M-v>"] = "RevertPopup",
			},
			status = {
				["j"] = false,
				["k"] = false,
				["o"] = "OpenTree",
				-- ["q"] = "Close",
				["I"] = "InitRepo",
				["<M-1>"] = "Depth1",
				["<M-2>"] = "Depth2",
				["<M-3>"] = "Depth3",
				["<M-4>"] = "Depth4",
				["Q"] = "Command",
				["<tab>"] = "Toggle",
				["za"] = "Toggle",
				["zo"] = "OpenFold",
				["zC"] = "Depth1",
				["zO"] = "Depth4",
				["x"] = "Discard",
				["s"] = "Stage",
				["S"] = "StageUnstaged",
				["<M-s>"] = "StageAll",
				["u"] = "Unstage",
				["K"] = "Untrack",
				["R"] = "Rename",
				["U"] = "UnstageStaged",
				["<S-M-r>"] = "ShowRefs",
				["<M-c>"] = "CommandHistory",
				["<M-y>"] = "YankSelected",
				["<c-r>"] = "RefreshBuffer",
				["<cr>"] = "GoToFile",
				["<s-cr>"] = "PeekFile",
				["<c-v>"] = "VSplitOpen",
				["<c-s>"] = "SplitOpen",
				["<c-t>"] = "TabOpen",
				["{"] = "GoToPreviousHunkHeader",
				["}"] = "GoToNextHunkHeader",
				["<C-Up>"] = "GoToPreviousHunkHeader",
				["<C-Down>"] = "GoToNextHunkHeader",
				["[c"] = "OpenOrScrollUp",
				["]c"] = "OpenOrScrollDown",
				["<M-Up>"] = "PeekUp",
				["<M-Down>"] = "PeekDown",
				["<c-n>"] = "NextSection",
				["<c-p>"] = "PreviousSection",
			},
		},
	},
}
